table Fato_Artilheiros
	lineageTag: fb3ee469-164b-4d5a-9738-2a46576efaec

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 2791254a-a626-42f0-96f4-11fafef7bc5e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Jogador
		dataType: string
		lineageTag: 2b73b238-a542-4c72-a120-e88a9faa9e90
		summarizeBy: none
		sourceColumn: Jogador

		annotation SummarizationSetBy = Automatic

	column Seleção
		dataType: string
		lineageTag: a7c53f74-f0b1-4099-a411-ebe8be51e247
		summarizeBy: none
		sourceColumn: Seleção

		annotation SummarizationSetBy = Automatic

	column 'Gols na Copa 2026'
		dataType: string
		lineageTag: 6564a559-6218-4a0d-b25f-912d5783cdfd
		summarizeBy: none
		sourceColumn: Gols na Copa 2026

		annotation SummarizationSetBy = Automatic

	column Observação
		dataType: string
		lineageTag: ae53c28f-939a-4a46-8e6d-c724ce681981
		summarizeBy: none
		sourceColumn: Observação

		annotation SummarizationSetBy = Automatic

	/// Gols do jogador na Copa 2026, extraído do número líder do texto (trata casos como '3 (só na disputa de 3º lugar)'). Origem ideal: Power Query numérico.
	column Gols = VAR t = TRIM('Fato_Artilheiros'[Gols na Copa 2026]) VAR posSpace = SEARCH(" ", t, 1, LEN(t) + 1) VAR posParen = SEARCH("(", t, 1, LEN(t) + 1) VAR cut = MIN(posSpace, posParen) - 1 RETURN VALUE(LEFT(t, cut))
		dataType: int64
		formatString: 0
		lineageTag: 23373565-11f5-4a89-9a4a-93764883565b
		summarizeBy: sum

	partition Artilheiros = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Enrico\Geral\BI\Youtube\Power BI do ZERO ao Dashboard Completo\Aula 01\Copa do Mundo 2026.xlsx"), null, true),
				    Artilheiros_Sheet = Fonte{[Item="Artilheiros",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Artilheiros_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#", Int64.Type}, {"Jogador", type text}, {"Seleção", type text}, {"Gols na Copa 2026", type any}, {"Observação", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"#", "ID"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

